defaultSemverRangePrefix: ''

packageExtensions:
  express-zod-api@8.4.0:
    dependencies:
      '@types/connect': 'npm:@types/connect@3.4.35'
      '@types/express-serve-static-core': 'npm:@types/express-serve-static-core@4.17.31'
      '@types/qs': 'npm:@types/qs@6.9.7'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
